unstable_features = true
max_width = 120
array_width = 100
attr_fn_like_width = 100
fn_call_width = 100
edition = "2018"
fn_single_line = true
hard_tabs = true
match_block_trailing_comma = true
merge_imports = true
newline_style = "Unix"
overflow_delimited_expr = true
reorder_impl_items = true
reorder_imports = true
group_imports = "StdExternalCrate"
required_version = "2.0.0-rc.2"
single_line_if_else_max_width = 100
struct_lit_width = 100
use_field_init_shorthand = true
where_single_line = true